"""
app.services.color_resolver
───────────────────────────

Translates Spanish color descriptions (as generated by Gemma 4)
into standardized CSS hex color strings for use in the Roblox renderer.
"""

from typing import Optional

# Spanish-language color aliases used by Gemma 4 → CSS hex values
COLOR_MAP: dict[str, str] = {
    "azul": "#4488FF", "azul oceánico": "#0066AA", "azul cielo": "#87CEEB",
    "azul oscuro": "#003399", "azul claro": "#66AAFF", "azul marino": "#001F5B",
    "azul eléctrico": "#007FFF",
    "rojo": "#FF4444", "naranja": "#FF8800", "naranja ardiente": "#FF6600",
    "rojo oscuro": "#990000", "coral": "#FF7F50", "rojo marciano": "#C1440E",
    "amarillo": "#FFEE00", "dorado": "#FFD700", "oro": "#FFD700",
    "amarillo solar": "#FFF176", "amarillo brillante": "#FFFF00",
    "verde": "#44CC66", "verde lima": "#32CD32", "verde oscuro": "#006400",
    "verde esmeralda": "#50C878", "verde neón": "#39FF14",
    "cian": "#00FFFF", "turquesa": "#40E0D0",
    "morado": "#9B59B6", "violeta": "#8A2BE2", "rosa": "#FF69B4",
    "magenta": "#FF00FF", "lila": "#B39DDB",
    "blanco": "#FFFFFF", "gris": "#808080", "gris claro": "#C0C0C0",
    "gris oscuro": "#404040", "plateado": "#C0C0C0", "plata": "#C0C0C0",
    "negro": "#111111",
    "marrón": "#8B4513", "café": "#8B4513", "beige": "#F5F5DC",
    "tierra": "#964B00", "concreto": "#9E9E9E", "cemento": "#8D8D8D",
    "naranja joviano": "#C4A24A", "azul tierra": "#1B6CA8",
}

_FALLBACK = "#AAAAAA"


def resolve(hint: Optional[str]) -> str:
    """Return a CSS hex string for the given Spanish color hint.

    Performs an exact match first, then a substring search, and
    finally falls back to mid-gray if no match is found.
    """
    if not hint:
        return _FALLBACK
    h = hint.lower().strip()
    if h in COLOR_MAP:
        return COLOR_MAP[h]
    for key, val in COLOR_MAP.items():
        if key in h or h in key:
            return val
    return _FALLBACK
